/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-11-29 12:03:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddToCartDisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Allianz/Desktop/java/OnlineShopping/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OnlineShopping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("jar:file:/C:/Users/Allianz/Desktop/java/OnlineShopping/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OnlineShopping/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1574076716202L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Book Store Template, Free CSS Template, TemplateMo.com</title>\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Book Store Template, Free CSS Template, CSS Website Layout, CSS, HTML, TemplateMo.com\" />\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Book Store Template, Free CSS Template, Download CSS Website from TemplateMo.com\" />\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--  Free CSS Templates from www.templatemo.com -->\r\n");
      out.write("\t<div id=\"templatemo_container\">\r\n");
      out.write("\t\t<div id=\"templatemo_menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"current\">Search</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">Books</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">New Releases</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Company</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end of menu -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"templatemo_header\">\r\n");
      out.write("\t\t\t<div id=\"templatemo_special_offers\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span>25%</span> discounts for purchase over $ 40\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" style=\"margin-left: 50px;\">Read more...</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"templatemo_new_books\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>Suspen disse</li>\r\n");
      out.write("\t\t\t\t\t<li>Maece nas metus</li>\r\n");
      out.write("\t\t\t\t\t<li>In sed risus ac feli</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<a href=\"#\" style=\"margin-left: 50px;\">Read more...</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end of header -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"templatemo_content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"templatemo_content_left\">\r\n");
      out.write("\t\t\t\t<div class=\"templatemo_content_left_section\">\r\n");
      out.write("\t\t\t\t\t<h1>Categories</h1>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">Donec accumsan urna</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">Proin vulputate justo</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">In sed risus ac feli</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Aliquam tristique dolor</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Maece nas metus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Sed pellentesque placerat</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Suspen disse</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Maece nas metus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">In sed risus ac feli</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"templatemo_content_left_section\">\r\n");
      out.write("\t\t\t\t\t<h1>Bestsellers</h1>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Vestibulum ullamcorper</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Maece nas metus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">In sed risus ac feli</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Praesent mattis varius</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Maece nas metus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">In sed risus ac feli</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.flashmo.com\" target=\"_parent\">Flash\r\n");
      out.write("\t\t\t\t\t\t\t\tTemplates</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.templatemo.com\" target=\"_parent\">CSS\r\n");
      out.write("\t\t\t\t\t\t\t\tTemplates</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.webdesignmo.com\" target=\"_parent\">Web\r\n");
      out.write("\t\t\t\t\t\t\t\tDesign</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.photovaco.com\" target=\"_parent\">Free\r\n");
      out.write("\t\t\t\t\t\t\t\tPhotos</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"templatemo_content_left_section\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://validator.w3.org/check?uri=referer\"><img\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 0; width: 88px; height: 31px\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"http://www.w3.org/Icons/valid-xhtml10\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Valid XHTML 1.0 Transitional\" width=\"88\" height=\"31\"\r\n");
      out.write("\t\t\t\t\t\tvspace=\"8\" border=\"0\" /></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://jigsaw.w3.org/css-validator/check/referer\"><img\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 0; width: 88px; height: 31px\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"http://jigsaw.w3.org/css-validator/images/vcss-blue\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Valid CSS!\" vspace=\"8\" border=\"0\" /></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end of content left -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"templatemo_content_right\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\tItem's added to <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'s</span>WishList....\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"image_panel\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/templatemo_image_02.jpg\" alt=\"CSS Template\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"100\" height=\"150\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table border=2>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Sr.No</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Product id</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Product Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Place order</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end of content right -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"cleaner_with_height\">&nbsp;</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end of content -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"templatemo_footer\">\r\n");
      out.write("\t\t\t<a href=\"index.html\">Home</a> | <a href=\"index.html\">Search</a> | <a\r\n");
      out.write("\t\t\t\thref=\"index.html\">Books</a> | <a href=\"#\">New Releases</a> | <a\r\n");
      out.write("\t\t\t\thref=\"#\">FAQs</a> | <a href=\"#\">Contact Us</a><br /> Copyright ©\r\n");
      out.write("\t\t\t2048 <a href=\"#\"><strong>Your Company Name</strong></a> | <a\r\n");
      out.write("\t\t\t\thref=\"http://www.iwebsitetemplate.com\" target=\"_parent\">Website\r\n");
      out.write("\t\t\t\tTemplates</a> by <a href=\"http://www.templatemo.com\" target=\"_parent\">Free\r\n");
      out.write("\t\t\t\tCSS Templates</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end of footer -->\r\n");
      out.write("\t\t<!--  Free CSS Template www.templatemo.com -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of container -->\r\n");
      out.write("\t<div align=center>\r\n");
      out.write("\t\tThis template downloaded form <a\r\n");
      out.write("\t\t\thref='http://all-free-download.com/free-website-templates/'>free\r\n");
      out.write("\t\t\twebsite templates</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /AddToCartDisplay.jsp(120,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/AddToCartDisplay.jsp(120,5) '${addToCartList1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${addToCartList1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /AddToCartDisplay.jsp(120,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("addToCartList");
      // /AddToCartDisplay.jsp(120,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addToCartList.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productNameList[status.index]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addToCartList.total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addToCartList.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td><a href=\"OrderController?action=getAllOrderByUserName\">Order Now</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
